#!/bin/bash
#    copyright Copyright 2013 Matt R. Flax <flatmax@flatmax.org> All Rights Reserved.
#
#    This code has a restricted license, you may not use this code without the permission of Matt Flax.
#
# Author Matt Flax <flatmax@flatmax.org>

# clean all files which are autogenerated
make distclean
mv m4/emscripten.m4 /tmp
rm -rf autom4te.cache aclocal.m4 m4/* missing config.sub COPYING config.guess configure depcomp install-sh config.h.in ltmain.sh   Makefile.in src/Makefile.in test/Makefile.in INSTALL api/Makefile.in .deps  gtkiostream-1* src/AudioMask/.deps a.out*
mv /tmp/emscripten.m4 m4
find . -name '*~' | xargs rm -f
find . -name '.deps' | xargs rm -rf
find . -name '.libs' | xargs rm -rf
find . -name 'octave-core' | xargs rm -f
find . -name 'Makefile.in' | xargs rm
rm -f compile
#rm -rf config.log config.h Makefile
